import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHome } from '@fortawesome/free-solid-svg-icons';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Group C Movie App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Link href="/"> <a><FontAwesomeIcon icon={faHome} className='home' /></a></Link>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
